### ISSUE TITLE
Verify login functionality with invalid login & password

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#1]
test case - Verify login functionality with invalid login & password

**Comment by mahidhar1g** [comment]
This is the test case template for the issue (Test Scenario 1)
[Test_Admin_Login (1).xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15149883/Test_Admin_Login.1.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_1_admin_login.py

Screenshot of the test
<img width="1357" alt="Screenshot 2024-04-28 at 8 27 36 AM" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/64c28b5e-1be3-475b-92bd-6ec69af00a59">
