### ISSUE TITLE
ORCID user sign up with MEICAN-testcases

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#16]
this issue will contain all the test cases related to MEICAN user signup

**Comment by mahidhar1g** [comment]
This is the test case template for the issue
[ORCID_User_Sign_Up_MEICAN.xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15140638/ORCID_User_Sign_Up_MEICAN.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_orcid_user_signup_with_meican.py

Screenshot of the test
<img width="1356" alt="orcid user" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/c80fd38d-0010-4e56-a142-e35b9c5adb18">
