### ISSUE TITLE
Test - assign read, update delete permissions to SDX circuit role

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#18]
![image](https://github.com/atlanticwave-sdx/meican-testing/assets/104851066/dc5843cc-9ce3-4e34-a579-3d77594c6aee)

Test case: Modifying the group SDX Circuit as an admin. When a new Meican instance is created, by default only a create permission will be assigned to the SDX Circuit group. The read, update, and delete permissions will not be given. This test case is about giving the read, update, and delete permissions to the SDX Circuit Group.

**Comment by mahidhar1g** [comment]
This is the test case template for the issue
[Test SDX Circuit Group Permissions.xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15167441/Test.SDX.Circuit.Group.Permissions.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/18-test-assign-read-update-delete-permissions-to-sdx-circuit-role/tests/test_sdx_circuit_group_permissions.py

This is the screenshot
<img width="1349" alt="sdx circuit permissions" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/bbb4323e-586f-419e-87d8-ef3769a6380c">
