### ISSUE TITLE
Test - assign SDX circuit role to a user

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#19]
![image](https://github.com/atlanticwave-sdx/meican-testing/assets/104851066/ac572805-645d-45b9-95b8-3d83d1609ec2)

Assigning the SDX Circuit role to the user (Selenium Testing User in this case)

**Comment by mahidhar1g** [comment]
This is the test case template for the issue
[Assigning SDX Circuit Group to the user.xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15167650/Assigning.SDX.Circuit.Group.to.the.user.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/19-test-assign-sdx-circuit-role-to-a-user/tests/test_assign_sdx_circuit_role.py

This is the screenshot
<img width="1351" alt="assign sdx circuit" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/95d49d50-c3e9-4a74-8387-e210e5d2648f">
