### ISSUE TITLE
Test-topology mapping on Meican UI

### ISSUE THREAD

**Issue by mahidhar1g** [atlanticwave-sdx/meican-testing#25]
Automating the topology mapping using Selenium and testing the same.

**Comment by usmanazFIU** [comment]
@mahidhar1g  Test case steps:
1- check if the endpoint returns http status code 200
2- parse all unique nodes (id)
3 - check if all nodes were mapped on the UI

**Comment by usmanazFIU** [comment]
@mahidhar1g I noticed that key value pair was not used in nodes-array. this is important as this can be a better way to check if all the nodes in that array were mapped to the UI. also when i added another node in the output the test still passed where as it should have been failed. Again, this wont be issue if you check all the keys in the array to be true before determining the test case result.
<img width="618" alt="image" src="https://github.com/atlanticwave-sdx/meican-testing/assets/104851066/9f8218a4-f37f-4a9c-9f9b-0dc0a6cbb21a">
<img width="1321" alt="image" src="https://github.com/atlanticwave-sdx/meican-testing/assets/104851066/f19065b9-fd4d-43a6-823c-901c6bfbccd8">

**Comment by usmanazFIU** [comment]
no it will not be added. that is the test itself. for instance it should fail if all nodes are not mapped to UI which were present in nodes array.

**Comment by usmanazFIU** [comment]
the node was added just for testing purpose. the test should fail if nodes was present in the nodes array but not mapped on the UI.

**Comment by mahidhar1g** [comment]
Got your point @usmanazFIU, I was doing exactly the opposite of that. I will make both the changes and let you know.

**Comment by mahidhar1g** [comment]
This is the test case template for the issue.



[Topology Mapping Test.xlsx](https://github.com/user-attachments/files/15745838/Topology.Mapping.Test.xlsx)
