### ISSUE TITLE
Verify login functionality with blank login & invalid password

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#3]
Verify login functionality with blank login & invalid password

**Comment by mahidhar1g** [comment]
This is the test case template for the issue (Test Scenario 3)
[Test_Admin_Login (1).xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15149883/Test_Admin_Login.1.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_3_admin_login.py

Screenshot of the test
<img width="1340" alt="Screenshot 2024-04-28 at 8 28 23 AM" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/8498eea9-2caf-4cde-9cab-f491affb3a96">
