### ISSUE TITLE
Verify login functionality with blank login and blank password

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#4]
Verify login functionality with blank login and blank password

**Comment by mahidhar1g** [comment]
This is the test case template for the issue
[Test_Admin_Login (1).xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15149883/Test_Admin_Login.1.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_2_admin_login.py

Screenshot of the test
<img width="1355" alt="Screenshot 2024-04-29 at 7 08 46 PM" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/8594c38c-b42e-471c-82ca-bb070a92fd09">
