### ISSUE TITLE
Verify login functionality with invalid login and blank password

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#5]
Verify login functionality with invalid login and blank password

**Comment by mahidhar1g** [comment]
This is the test case template for the issue (Test Scenario 4)
[Test_Admin_Login (1).xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15149883/Test_Admin_Login.1.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_4_admin_login.py

Screenshot of the test
<img width="1355" alt="Screenshot 2024-04-29 at 7 19 23 PM" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/eb49ae83-5256-40c4-a934-f4dc583dcf15">
