### ISSUE TITLE
Verify login functionality with blank login and valid password

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#6]
Verify login functionality with blank login valid password

**Comment by mahidhar1g** [comment]
This is the test case template for the issue (Test Scenario 5)
[Test_Admin_Login (1).xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15149883/Test_Admin_Login.1.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_5_admin_login.py

Screenshot of the test
<img width="1347" alt="Test5" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/437946a1-6e93-4aa8-8892-e9fcc5011c44">
