### ISSUE TITLE
Verify login functionality with valid login & password

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/meican-testing#8]
Verify login functionality with valid login & password

**Comment by mahidhar1g** [comment]
This is the test case template for the issue (Test Scenario 7)
[Test_Admin_Login (1).xlsx](https://github.com/atlanticwave-sdx/meican-testing/files/15149883/Test_Admin_Login.1.xlsx)

Test File - https://github.com/atlanticwave-sdx/meican-testing/blob/main/tests/test_7_admin_login.py

Screenshot of the test
<img width="1347" alt="Test7" src="https://github.com/atlanticwave-sdx/meican-testing/assets/156211533/82c485dc-6f0d-4379-bfc6-ccd6362784cd">
